# Generated by Django 4.1.6 on 2023-02-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_be', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouurseRegister',
            fields=[
                ('register_id', models.AutoField(db_column='register_id', primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(db_column='applicant_name', max_length=20)),
                ('contact_no', models.IntegerField(db_column='contact_no')),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('alternative_email', models.EmailField(blank=True, db_column='alternative_email', max_length=254)),
                ('address', models.CharField(db_column='address', max_length=50)),
                ('postal_code', models.IntegerField(db_column='postal_code')),
                ('FIN_NRIC_Passport_no', models.IntegerField(db_column='FIN_NRIC_Passport_no')),
                ('company_name', models.CharField(db_column='company_name', max_length=30)),
                ('membership_type', models.CharField(choices=[('Self', 'Self'), ('Company', 'Company')], db_column='membership_type', default='Self', max_length=20)),
                ('membership_no', models.IntegerField(db_column='membership_no')),
                ('payment', models.ForeignKey(db_column='payment', on_delete=django.db.models.deletion.PROTECT, to='payment.payment')),
                ('selected_course', models.ForeignKey(db_column='selected_course', on_delete=django.db.models.deletion.PROTECT, to='courses_be.newcourse')),
            ],
            options={
                'db_table': 'course_register',
            },
        ),
    ]
